name: Ahoy.js
ui: tape
html: test/template.html
scripts:
  - ahoy.js
  - test/test_helper.js
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 11..latest
  - name: ie
    version: 8
